---

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Create user
      include_role:
        name: init_setup
        tasks_from: acc_to_secm.yml

    - name: Install Docker
      include_role:
        name: install_docker
        tasks_from: install_docker.yml