   - name: Add a new user named demo
     user:
          name={{user}}
          password={{ demo_password }}

   - name: Add demo user to the sudoers
     copy:
          dest: "/etc/sudoers.d/{{user}}"
          content: "{{user}}  ALL=(ALL)  NOPASSWD: ALL"

   - name: Deploy SSH Key
     authorized_key: user={{user}}
                     key="{{ lookup('file', '/home/rogovam/.ssh/id_rsa.pub') }}"
                     state=present

   - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes

   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes

   - name: restart ssh
     service:
       state: restarted
       name: sshd